name: many-to-many-project
services:
 container1:
    image: mysql
    container_name: mysql_project_container
    environment:
      - MYSQL-ROOT_PASSWORD=mysql
      - MYSQL_TCP_PORT=1500
    network_mode: host
    volumes:
      - ~/project:/var/lib/mysql
